strumm:
  image: marcobaobao/strumm
  container_name: strumm
  restart: unless-stopped
  ports:
    - "8084:8080"
  volumes:
    - /mnt/merged/share/music:/music
    - /home/marco/.config/strumm:/config